language: node_js

cache: yarn

node_js:
    - "10"

before_deploy: yarn build
deploy:
    on:
        branch: master
        tag: true
    provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY