version: 2
general:
    branches:
        ignore: /^(?!master).*$/
jobs:
    lint:
        docker:
            - image: circleci/node:10.1
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn lint
    test:
        docker:
            - image: 'circleci/node:10.1'
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn test
    publish:
        docker:
            - image: 'circleci/node:10.1'
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn build
            - run: npm publish
workflows:
    version: 2
    run_tests:
        jobs:
            - test
            - lint
    publish_package:
        jobs:
            - test:
                filters:
                    tags:
                        only: /\d+\.\d+\.\d+.*/
            - lint:
                filters:
                    tags:
                        only: /\d+\.\d+\.\d+.*/
            - publish:
                requires:
                    - test
                    - lint
                filters:
                    tags:
                        only: /\d+\.\d+\.\d+.*/
